apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: cs4100320003d7a01f3
  azurestorageaccountkey: yUZuvy7kHWo9ogAx1VfkFrFmzbi0xTkZqNhh7Ox09TBFBYylABX2m4paY71PgW9eSwpqoJMq2gOD+AStfkLv8w==
